server:
  port: 8889

spring:
  redis:
    database: 0
    host: localhost
    port: 6379
    password: 123456
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
  data:
    mongodb:
      uri: mongodb://study:123@localhost:27017/study
